#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import re
from dataclasses import dataclass
from pathlib import Path


BEGIN_MARKER = "# BEGIN GENERATED CODEX AGENTS"
END_MARKER = "# END GENERATED CODEX AGENTS"

REPO_ROOT = Path(__file__).resolve().parent.parent
SHARED_AGENTS_DIR = REPO_ROOT / ".shared" / "agents"
GENERATED_DIR = REPO_ROOT / ".shared" / "generated" / "codex-agents"
CODEX_CONFIG = REPO_ROOT / ".codex" / "config.toml"

# Claude-style model metadata in the shared markdown can optionally map to a
# Codex model default. Files can override this with codex_model in front matter.
MODEL_MAP = {
    "haiku": "gpt-5.4-mini",
    "sonnet": "gpt-5.4",
    "opus": "gpt-5.4",
}

REASONING_EFFORT_MAP = {
    "haiku": "low",
    "sonnet": "medium",
    "opus": "high",
}


@dataclass
class AgentSpec:
    name: str
    description: str
    source_file: Path
    codex_model: str | None
    codex_model_reasoning_effort: str | None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Codex custom-agent config from shared markdown agent files."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if generated files or config are out of date.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    agent_specs = load_agent_specs()
    generated_files = build_generated_files(agent_specs)
    managed_block = build_managed_config_block(agent_specs)

    pending_updates: list[tuple[Path, str]] = []

    for path, content in generated_files.items():
        if read_text_or_empty(path) != content:
            pending_updates.append((path, content))

    config_content = read_text_or_empty(CODEX_CONFIG)
    updated_config = replace_managed_block(config_content, managed_block)
    if updated_config != config_content:
        pending_updates.append((CODEX_CONFIG, updated_config))

    if args.check:
        if pending_updates:
            for path, _ in pending_updates:
                print(path.relative_to(REPO_ROOT))
            return 1
        return 0

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in pending_updates:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    if pending_updates:
        for path, _ in pending_updates:
            print(f"updated {path.relative_to(REPO_ROOT)}")
    else:
        print("codex agent config already up to date")
    return 0


def load_agent_specs() -> list[AgentSpec]:
    specs: list[AgentSpec] = []
    for source_file in sorted(SHARED_AGENTS_DIR.glob("*.md")):
        front_matter = parse_front_matter(source_file)
        name = front_matter.get("name")
        description = summarize_description(front_matter.get("description", ""))
        if not name or not description:
            raise ValueError(f"{source_file} is missing required front matter")

        legacy_model = front_matter.get("model")
        codex_model = front_matter.get("codex_model") or MODEL_MAP.get(legacy_model)
        codex_reasoning = front_matter.get("codex_model_reasoning_effort")
        if not codex_reasoning and legacy_model:
            codex_reasoning = REASONING_EFFORT_MAP.get(legacy_model)

        specs.append(
            AgentSpec(
                name=str(name),
                description=description,
                source_file=source_file,
                codex_model=str(codex_model) if codex_model else None,
                codex_model_reasoning_effort=(
                    str(codex_reasoning) if codex_reasoning else None
                ),
            )
        )

    return specs


def build_generated_files(agent_specs: list[AgentSpec]) -> dict[Path, str]:
    files: dict[Path, str] = {}
    for spec in agent_specs:
        lines = [
            "# Generated by scripts/sync_codex_agents.py. Do not edit by hand.",
            f'name = "{toml_escape(spec.name)}"',
            f'description = "{toml_escape(spec.description)}"',
            f'model_instructions_file = "{toml_escape(relative_path(GENERATED_DIR / f"{spec.name}.toml", spec.source_file))}"',
        ]
        if spec.codex_model:
            lines.append(f'model = "{toml_escape(spec.codex_model)}"')
        if spec.codex_model_reasoning_effort:
            lines.append(
                f'model_reasoning_effort = "{toml_escape(spec.codex_model_reasoning_effort)}"'
            )
        files[GENERATED_DIR / f"{spec.name}.toml"] = "\n".join(lines) + "\n"
    return files


def build_managed_config_block(agent_specs: list[AgentSpec]) -> str:
    lines = [
        BEGIN_MARKER,
        "# Generated by scripts/sync_codex_agents.py from .shared/agents/*.md.",
    ]
    for spec in agent_specs:
        lines.extend(
            [
                "",
                f"[agents.{spec.name}]",
                f'description = "{toml_escape(spec.description)}"',
                f'config_file = "{toml_escape(relative_path(CODEX_CONFIG, GENERATED_DIR / f"{spec.name}.toml"))}"',
                f'nickname_candidates = ["{toml_escape(spec.name)}"]',
            ]
        )
    lines.extend(["", END_MARKER, ""])
    return "\n".join(lines)


def replace_managed_block(config_text: str, managed_block: str) -> str:
    if BEGIN_MARKER in config_text and END_MARKER in config_text:
        pattern = re.compile(
            rf"{re.escape(BEGIN_MARKER)}.*?{re.escape(END_MARKER)}\n?",
            flags=re.DOTALL,
        )
        updated = pattern.sub(managed_block, config_text, count=1)
        return updated

    base = config_text.rstrip()
    if base:
        return f"{base}\n\n{managed_block}"
    return managed_block


def parse_front_matter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path} does not start with YAML front matter")

    _, _, remainder = text.partition("---\n")
    front_matter, separator, _ = remainder.partition("\n---\n")
    if not separator:
        raise ValueError(f"{path} is missing the closing front matter delimiter")

    return parse_simple_yaml(front_matter)


def parse_simple_yaml(front_matter: str) -> dict[str, str]:
    data: dict[str, str] = {}
    lines = front_matter.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        if not line.strip():
            index += 1
            continue

        match = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if not match:
            raise ValueError(f"Unsupported front matter line: {line!r}")

        key = match.group(1)
        value = match.group(2)
        if value.startswith('"') and not is_closed_quoted_scalar(value):
            parts = [value]
            index += 1
            while index < len(lines):
                parts.append(lines[index])
                candidate = "\n".join(parts)
                if is_closed_quoted_scalar(candidate):
                    value = candidate
                    break
                index += 1
            else:
                raise ValueError(f"Unterminated quoted scalar for key {key!r}")

        data[key] = parse_scalar(value)
        index += 1

    return data


def parse_scalar(value: str) -> str:
    value = value.strip()
    if not value:
        return ""
    if value.startswith('"') and is_closed_quoted_scalar(value):
        inner = value[1:-1]
        inner = inner.replace("\\n", "\n")
        inner = inner.replace('\\"', '"')
        inner = inner.replace("\\\\", "\\")
        return inner
    return value


def is_closed_quoted_scalar(value: str) -> bool:
    if not value.startswith('"') or not value.endswith('"'):
        return False
    backslashes = 0
    for char in reversed(value[:-1]):
        if char == "\\":
            backslashes += 1
        else:
            break
    return backslashes % 2 == 0


def summarize_description(value: str) -> str:
    summary = re.split(r"Examples?:|<example>", value, maxsplit=1)[0]
    summary = summary.replace("\\n", " ")
    summary = summary.replace("\\", " ")
    return " ".join(summary.split())


def relative_path(from_path: Path, to_path: Path) -> str:
    return os.path.relpath(to_path, start=from_path.parent).replace(os.sep, "/")


def read_text_or_empty(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


if __name__ == "__main__":
    raise SystemExit(main())
